server {
    listen 443 ssl;
    server_name  example.com; # replace with your own domain here

    ssl_certificate      /etc/letsencrypt/live/example.com/fullchain.pem; # replace with your own cert, possibly self signed
    ssl_certificate_key  /etc/letsencrypt/live/example.com/privkey.pem; # replace with your own key

    root /var/www;

    location /server/ {
        proxy_pass http://localhost:3000; # nodeJs server
    }

    location / {
        proxy_pass http://localhost:32817; # reactnative metro app
    }
}
